### ISSUE TITLE
Sand - No module named sand

### ISSUE THREAD

**Issue by pocock** [inconvergent/fast-sand-paint#6]
on Mac osx 10.8 with python 2.4, 2.7, and 3.6 installed. numpy scipy.... get this error

  File "./example.py", line 5, in <module>
    from sand import Sand
ImportError: No module named sand

Help would be appreciated by this inconvergent newbie. super repos! thanks

**Comment by inconvergent** [comment]
note: this code only works with python 3. 

did you try running the install script in the same folder as example.py?
